version: '3.5'
services:
  database:
    image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    hostname: database
    container_name: database
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
      - "./database/init1.sql:/docker-entrypoint-initdb.d/1.sql"
    networks:
      - backnet
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306
      - 33060
  backend:
    build: backend
    image: backend
    hostname: backend
    container_name: backend
    restart: always
    secrets:
      - db-password
    volumes:
      - "./backend/app.py:/code/app.py"
    networks:
      - backnet
      - frontnet
    depends_on:
      database:
        condition: service_healthy
    expose:
      - 5000
  proxy:
    build: proxy
    image: proxy
    hostname: proxy
    container_name: proxy
    restart: always
    ports:
      - 80:80
    volumes:
      - "./html/:/usr/share/nginx/html"
    depends_on: 
      - backend
    networks:
      - frontnet

  newman:
    image: gitlab.sdu.dk:5050/odw-e2020/postman
    command: sleep 3600
    restart: on-failure
    networks:
      backnet:
volumes:
  db-data:
secrets:
  db-password:
    file: database/password.txt
networks:
  backnet:
    name: backnet
  frontnet:
    name: frontnet